version: "3.8"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./images:/usr/share/nginx/html/images:ro
      - ./pages:/usr/share/nginx/html/pages:ro
